services:
  unubot:
    build: .
    image: reunu/unubot:latest
    restart: unless-stopped
    env_file: .env
    environment:
      UNUBOT_CONTENT_DIR: /app/content
    volumes:
      - ./content:/app/content:ro
